text = '''The word may have started to acquire associations of immorality as early as the 14th century, but had certainly acquired them by the 17th.[1] By the late 17th century it had acquired the specific meaning of "addicted to pleasures and dissipations",[9] an extension of its primary meaning of "carefree" implying "uninhibited by moral constraints". A gay woman was a prostitute, a gay man a womanizer, and a gay house a brothel.[1] The use of gay to mean "homosexual" was often an extension of its application to prostitution: a gay boy was a young man or boy serving male clients.[10] Similarly, a gay cat was a young male apprenticed to an older hobo, commonly exchanging sex and other services for protection and tutelage.[1] The application to homosexuality was also an extension of the word's sexualized connotation of "carefree and uninhibited", which implied a willingness to disregard conventional or respectable sexual mores. Such usage, documented as early as the 1920s, was likely present before the 20th century,[1] although it was initially more commonly used to imply heterosexually unconstrained lifestyles, as in the once-common phrase "gay Lothario",[11] or in the title of the book and film The Gay Falcon (1941), which concerns a womanizing detective whose first name is "Gay". Similarly, Fred Gilbert and G. H. MacDermott's music hall song of the 1880s, "Charlie Dilke Upset the Milk" – "Master Dilke upset the milk/When taking it home to Chelsea;/ The papers say that Charlie's gay/Rather a wilful wag!" – referred to Sir Charles Dilke's alleged heterosexual impropriety.[12] Giving testimony in court in 1889, the rentboy John Saul stated: "I occasionally do odd-jobs for different gay people."[13] Well into the mid 20th century a middle-aged bachelor could be described as "gay", indicating that he was unattached and therefore free, without any implication of homosexuality. This usage could apply to women too. The British comic strip Jane, first published in the 1930s, described the adventures of Jane Gay. Far from implying homosexuality, it referred to her free-wheeling lifestyle with plenty of boyfriends (while also punning on Lady Jane Grey).

A passage from Gertrude Stein's Miss Furr & Miss Skeene (1922) is possibly the first traceable published use of the word to refer to a homosexual relationship. According to Linda Wagner-Martin (Favored Strangers: Gertrude Stein and her Family (1995)) the portrait "featured the sly repetition of the word gay, used with sexual intent for one of the first times in linguistic history," and Edmund Wilson (1951, quoted by James Mellow in Charmed Circle (1974)) agreed.[14] For example:

They were ... gay, they learned little things that are things in being gay, ... they were quite regularly gay.

— Gertrude Stein, 1922
Bringing Up Baby (1938) was the first film to use the word gay in apparent reference to homosexuality. In a scene in which the Cary Grant character's clothes have been sent to the cleaners, he is forced to wear a woman’s feather-trimmed robe. When another character asks about his robe, he responds, "Because I just went gay all of a sudden!" Since this was a mainstream film at a time when the use of the word to refer to cross-dressing (and, by extension, homosexuality) would still be unfamiliar to most film-goers, the line can also be interpreted to mean, "I just decided to do something frivolous."[15]

The word continued to be used with the dominant meaning of "carefree", as evidenced by the title of The Gay Divorcee (1934), a musical film about a heterosexual couple.

Shift to specifically homosexual
By the mid-20th century, gay was well established in reference to hedonistic and uninhibited lifestyles[9] and its antonym straight, which had long had connotations of seriousness, respectability, and conventionality, had now acquired specific connotations of heterosexuality.[16] In the case of gay, other connotations of frivolousness and showiness in dress ("gay apparel") led to association with camp and effeminacy. This association no doubt helped the gradual narrowing in scope of the term towards its current dominant meaning, which was at first confined to subcultures. Gay was the preferred term since other terms, such as queer, were felt to be derogatory.[17] Homosexual is perceived as excessively clinical,[18][19][20] since the sexual orientation now commonly referred to as "homosexuality" was at that time a mental illness diagnosis in the Diagnostic and Statistical Manual of Mental Disorders (DSM).

In mid-20th century Britain, where male homosexuality was illegal until the Sexual Offences Act 1967, to openly identify someone as homosexual was considered very offensive and an accusation of serious criminal activity. Additionally, none of the words describing any aspect of homosexuality were considered suitable for polite society. Consequently, a number of euphemisms were used to hint at suspected homosexuality. Examples include "sporty" girls and "artistic" boys,[21] all with the stress deliberately on the otherwise completely innocent adjective.

The sixties marked the transition in the predominant meaning of the word gay from that of "carefree" to the current "homosexual".

In the British comedy-drama film Light Up the Sky! (1960), directed by Lewis Gilbert, about the antics of a British Army searchlight squad during World War II, there is a scene in the mess hut where the character played by Benny Hill proposes an after-dinner toast. He begins, "I'd like to propose..." at which point a fellow diner, played by Sidney Tafler, interjects "Who to?", suggesting a proposal of marriage. The Benny Hill character responds, "Not to you for start, you ain't my type". He then adds in mock doubt, "Oh, I don't know, you're rather gay on the quiet."

By 1963, a new sense of the word gay was known well enough to be used by Albert Ellis in his book The Intelligent Woman's Guide to Man-Hunting. Similarly, Hubert Selby, Jr. in his 1964 novel Last Exit to Brooklyn, could write that a character "took pride in being a homosexual by feeling intellectually and esthetically superior to those (especially women) who weren't gay...."[22] Later examples of the original meaning of the word being used in popular culture include the theme song to the 1960–1966 animated TV series The Flintstones, whereby viewers are assured that they will "have a gay old time." Similarly, the 1966 Herman's Hermits song "No Milk Today", which became a Top 10 hit in the UK and a Top 40 hit in the U.S., included the lyric "No milk today, it was not always so / The company was gay, we'd turn night into day."[23] In June 1967, the headline of the review of the Beatles' Sgt. Pepper's Lonely Hearts Club Band album in the British daily newspaper The Times stated, "The Beatles revive hopes of progress in pop music with their gay new LP".[24] Yet in the same year, The Kinks recorded "David Watts".[25] Ostensibly about schoolboy envy, the song also operated as an in-joke, as related in Jon Savage's "The Kinks: The Official Biography", because the song took its name from a homosexual promoter they'd encountered who'd had romantic designs on songwriter Ray Davies' teenage brother; and the lines "he is so gay and fancy free" attest to the ambiguity of the word's meaning at that time, with the second meaning evident only for those in the know.[26] As late as 1970, the first episode of The Mary Tyler Moore Show has the demonstrably straight Mary Richards' downstairs neighbor, Phyllis, breezily declaiming that Mary is, at age 30, still "young and gay."

There is little doubt that the homosexual sense is a development of the word's traditional meaning, as described above. It has nevertheless been claimed that gay stands for "Good As You", but there is no evidence for this: it is a backronym created as popular etymology.[27]
'''


text1 = '''China, officially the People's Republic of China (PRC), is a unitary sovereign state in East Asia and the world's most populous country, with a population of around 1.404 billion.[13] Covering approximately 9.6 million square kilometres (3.7 million square miles), it is the world's second-largest state by land area[19] and third- or fourth-largest by total area.[j] Governed by the Communist Party of China, it exercises jurisdiction over 22 provinces, five autonomous regions, four direct-controlled municipalities (Beijing, Tianjin, Shanghai, and Chongqing) and the Special Administrative Regions Hong Kong and Macau, also claiming sovereignty over Taiwan.

China emerged as one of the world's earliest civilizations in the fertile basin of the Yellow River in the North China Plain. For millennia, China's political system was based on hereditary monarchies, or dynasties, beginning with the semi-legendary Xia dynasty. Since then, China has expanded, fractured, and re-unified numerous times. In 1912, the Republic of China (ROC) replaced the last dynasty and ruled the Chinese mainland until 1949, when it was defeated by the communist People's Liberation Army in the Chinese Civil War. The Communist Party established the People's Republic of China in Beijing on 21 September 1949, while the ROC government retreated to Taiwan with its present de facto capital in Taipei. Both the ROC and PRC continue to claim to be the legitimate government of all China, though the latter has more recognition in the world and controls more territory.

Since the introduction of economic reforms in 1978, China's economy has been one of the world's fastest-growing. As of 2016, it is the world's second-largest economy by nominal GDP and largest by purchasing power parity (PPP). China is also the world's largest exporter and second-largest importer of goods.[20] China is a recognized nuclear weapons state and has the world's largest standing army and second-largest defense budget.[21][22] The PRC is a member of the United Nations, as it replaced the ROC as a permanent member of the U.N. Security Council in 1971. China is also a member of numerous formal and informal multilateral organizations, including the WTO, APEC, BRICS, the Shanghai Cooperation Organization (SCO), the BCIM and the G20. China is a great power and a major regional power within Asia, and has been characterized as a potential superpower.[23][24]
'''


math = '''Mathematics (from Greek μάθημα máthēma, "knowledge, study, learning") is the study of topics such as space,[1] quantity (numbers),[1] structure,[2] and change.[3][4][5] There is a range of views among mathematicians and philosophers as to the exact scope and definition of mathematics.[6][7]

Mathematicians seek out patterns[8][9] and use them to formulate new conjectures. Mathematicians resolve the truth or falsity of conjectures by mathematical proof. When mathematical structures are good models of real phenomena, then mathematical reasoning can provide insight or predictions about nature. Through the use of abstraction and logic, mathematics developed from counting, calculation, measurement, and the systematic study of the shapes and motions of physical objects. Practical mathematics has been a human activity from as far back as written records exist. The research required to solve mathematical problems can take years or even centuries of sustained inquiry.

Rigorous arguments first appeared in Greek mathematics, most notably in Euclid's Elements. Since the pioneering work of Giuseppe Peano (1858–1932), David Hilbert (1862–1943), and others on axiomatic systems in the late 19th century, it has become customary to view mathematical research as establishing truth by rigorous deduction from appropriately chosen axioms and definitions. Mathematics developed at a relatively slow pace until the Renaissance, when mathematical innovations interacting with new scientific discoveries led to a rapid increase in the rate of mathematical discovery that has continued to the present day.[10][page needed]

Galileo Galilei (1564–1642) said, "The universe cannot be read until we have learned the language and become familiar with the characters in which it is written. It is written in mathematical language, and the letters are triangles, circles and other geometrical figures, without which means it is humanly impossible to comprehend a single word. Without these, one is wandering about in a dark labyrinth."[11] Carl Friedrich Gauss (1777–1855) referred to mathematics as "the Queen of the Sciences".[12][page needed] Benjamin Peirce (1809–1880) called mathematics "the science that draws necessary conclusions".[13] David Hilbert said of mathematics: "We are not speaking here of arbitrariness in any sense. Mathematics is not like a game whose tasks are determined by arbitrarily stipulated rules. Rather, it is a conceptual system possessing internal necessity that can only be so and by no means otherwise."[14][page needed] Albert Einstein (1879–1955) stated that "as far as the laws of mathematics refer to reality, they are not certain; and as far as they are certain, they do not refer to reality."[15]

Mathematics is essential in many fields, including natural science, engineering, medicine, finance and the social sciences. Applied mathematics has led to entirely new mathematical disciplines, such as statistics and game theory. Mathematicians also engage in pure mathematics, or mathematics for its own sake, without having any application in mind. There is no clear line separating pure and applied mathematics, and practical applications for what began as pure mathematics are often discovered'''


sport = '''Sport (British English) or sports (American English) includes all forms of competitive physical activity or games which,[1] through casual or organised participation, aim to use, maintain or improve physical ability and skills while providing enjoyment to participants, and in some cases, entertainment for spectators.[2] Usually the contest or game is between two sides, each attempting to exceed the other. Some sports allow a tie game; others provide tie-breaking methods, to ensure one winner and one loser. A number of such two-sided contests may be arranged in a tournament producing a champion. Many sports leagues make an annual champion by arranging games in a regular sports season, followed in some cases by playoffs. Hundreds of sports exist, from those between single contestants, through to those with hundreds of simultaneous participants, either in teams or competing as individuals. In certain sports such as racing, many contestants may compete, each against each other, with one winner.

'''